name: Cloudflare Password Worker

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install PNPM
      - name: Install PNPM
        uses: pnpm/action-setup@v4

      # Install PNPM dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --optional

      # Upload worker
      - name: Upload worker
        run: pnpm exec wrangler deploy --config src/workers/Password/wrangler.json
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_WORKER_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
